### ISSUE TITLE
Wordle Scoreboard

### ISSUE THREAD

**Issue by CerineBnsd** [GDGAlgiers/BrainyBot2.0#28]
### Description
We're enjoying to play Wordle together on the community server. However, making manual score boards is painful, Brainy should take care of this! 

### To implement
The main features should be:
- [ ] Detect Wordle messages (Based on their format) 
- [x] Update the scores and save them based on sent messages.
- [x] React to sent messages to confirm receiving them (or reply to them with diverse messages)
- [x] `scoreboard` command to show the scoreboard

### To go further
- [ ] Launch a new session every night and create the thread automatically

**Comment by youben11** [comment]
While I really love how feature rich the issue is, I think it can be faster and simpler to implement with a single command that can be run on threads, the bot can parse the discussion and send the scoreboard at the end. It will have to parse the discussion on every run, however, it wouldn't require storing scores and watching for incoming messages.

We do aim for the full features described, but a simple solution can be implemented first I think.

**Comment by mohammed-elhaouari** [comment]
@youben11 I also see it this way. read & parse. though there is a limit on the number of messages you are able to fetch from API. so there must be some kind of pagination.
